services:
  db:
    container_name: db
    image: postgres:16.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  app:
    container_name: app
    build: .
    ports:
      - "4000:4000"
    develop:
      watch:
        - path: ./soplaya
          action: rebuild
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/postgres
      - SOPLAYA_CONFIG=config.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  data:
