services:
  db:
    container_name: db
    image: postgres:16.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data

  app:
    container_name: app
    build: .
    ports:
      - "4000:4000"
    develop:
      watch:
        - path: ./soplaya
          action: rebuild
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

volumes:
  data:
